require("brady.plugins-setup")
require("brady.core.options")
require("brady.core.keymaps")
require("brady.plugins.nvterm")
require("brady.plugins.harpoon")
require("brady.plugins.telescope")
require("brady.plugins.treesitter")
require("brady.plugins.gitsigns")
